In [1]:
## Numpy is the fundamental library for scientific computing in python 
## It provides support for array and matrices ( vectorized operations )

In [2]:
# Installation 
! pip install numpy

In [3]:
# Importing numpy 
import numpy as np

In [4]:
# 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1 , type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [6]:
arr2 = np.array((1,2,3,4,5,6,7,8,9))
print(arr2,type(arr2),arr2.shape)

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> (9,)


In [9]:
# 2-D array
arr3 = np.array([[1,2,3],[4,5,6]]) ## 2 rows and 3 columns 
print(arr3 , type(arr3) , arr3.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [10]:
arr4 = np.array([[1,2,3,4,5]]) # 1 row 5 columns 
print( arr4 , type(arr4) , arr4.shape)

[[1 2 3 4 5]] <class 'numpy.ndarray'> (1, 5)


In [11]:
# 3-D array
arr5 = np.array([[[1,2,3],[4,5,6]]])
print(arr5 , arr5.shape , arr5.ndim)

[[[1 2 3]
  [4 5 6]]] (1, 2, 3) 3


In [15]:
arr6 = np.array([[[2,3,5],[1,2,3],[4,5,6]],[[8,9,10],[7,8,9],[1,2,3]]])
print(arr6 , arr6.shape , arr6.ndim)

[[[ 2  3  5]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [ 7  8  9]
  [ 1  2  3]]] (2, 3, 3) 3


In [21]:
arr6 = np.array([1,2,3,4,5])

In [24]:
# reshape 
arr6.reshape(1,5) # 1 row and 5 columns 

array([[1, 2, 3, 4, 5]])

In [26]:
## arange function
arr= np.arange(1,10,2) # (start , stop(not inclusive) , step)
arr

array([1, 3, 5, 7, 9])

In [27]:
arr1 = np.arange(0,20,2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr3 = np.arange(1,20,3).reshape(1,7)
arr3

array([[ 1,  4,  7, 10, 13, 16, 19]])

In [30]:
arr3 = np.arange(1,20,3).reshape(7,1)
arr3

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16],
       [19]])

In [31]:
np.arange(1,19,4).reshape(5,1)

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]])

In [33]:
## np.ones and np.zeros 
# np.ones((rows,columns))
arr = np.ones((3,4)) # 3 rows and 4 columns 2-D array
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr1 = np.ones((4,4))
arr1


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
## np.zeros - generates 2-D array
arr2 = np.zeros((2,2))
arr2

array([[0., 0.],
       [0., 0.]])

In [38]:
arr3 = np.zeros((5,7))
arr3

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [40]:
## Identity matrix using np.eye - generates a square matrix in which diagonal elements are
## filled with ones and other with zeros 
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [45]:
# Attributes of Numpy array 
arr = np.array([[1,2,3],[4,5,6]])
print("Array = ",arr)
print("Shape = " ,arr.shape) # (rows , columns)
print("Number of Dimensions = ",arr.ndim) 
print("Datatype = " ,arr.dtype) # may vary based on platform 
print("Size (no. of elements ) = " , arr.size )
print("Item size (in bytes) = ",arr.itemsize) # may vary based on platform 

Array =  [[1 2 3]
 [4 5 6]]
Shape =  (2, 3)
Number of Dimensions =  2
Datatype =  int32
Size (no. of elements ) =  6
Item size (in bytes) =  4


In [46]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(arr1)
print(arr1.ndim) # 2
print(arr1.dtype) # int32
print(arr1.shape) # (3,4)
print(arr1.size) # 12
print(arr1.itemsize) # 4

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
2
int32
(3, 4)
12
4


In [51]:
arr2 =  np.array([[[1,2,3]],[[5,6,7]]])
print(arr2)
print(arr2.shape) # (2,1,3)
print(arr2.ndim) # 3
print(arr2.itemsize) # 4
print(arr2.dtype) # int32
print(arr2.size)

[[[1 2 3]]

 [[5 6 7]]]
(2, 1, 3)
3
4
int32
6


In [52]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
arr.shape #(2,2,4)

(2, 2, 4)

In [53]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,5],[1,2,3,4,5]],[[1,2,3,4,5],[5,6,7,8,5],[1,2,3,4,5]],[[1,2,3,4,5],[6,7,5,4,3],[2,1,2,3,2]]])
arr.shape #(3,3,5)

(3, 3, 5)

In [54]:
## Numpy Vectorized Operations 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,11,12,13,14])

## element wise addition
print(arr1 + arr2)

## element wise subtraction 
print(arr1 - arr2)

## element wise multiplication 
print(arr1 * arr2)

## element wise division 
print(arr1 / arr2)


[11 13 15 17 19]
[-9 -9 -9 -9 -9]
[10 22 36 52 70]
[0.1        0.18181818 0.25       0.30769231 0.35714286]


In [55]:
a = np.array([10,20,30])
b = np.array([30,20,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)

[40 40 40]
[-20   0  20]
[300 400 300]
[0.33333333 1.         3.        ]
[0 1 3]
[10  0  0]


In [58]:
## Mathematical Functions 

arr = np.array([1,2,3,4,5])
# square root
print(np.sqrt(arr))

# exponential 
print(np.exp(arr))

# sine 
print(np.sin(arr))

# natural log 
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [63]:
## Array slicing and Indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
arr[0]

array([1, 2, 3, 4])

In [65]:
arr[1]

array([5, 6, 7, 8])

In [66]:
arr[2]

array([ 9, 10, 11, 12])

In [67]:
# arr[row][column] or arr[row,column]
arr[0][2]

3

In [68]:
arr[0,2]

3

In [69]:
arr[2][3]

12

In [70]:
arr[2,3]

12

In [71]:
arr[1,1]

6

In [72]:
arr[1][1]

6

In [73]:
## slicing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
arr[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
arr[0:2,:2] # arr[rows,columns]

array([[1, 2],
       [5, 6]])

In [83]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [88]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [89]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [90]:
arr[-1]

array([ 9, 10, 11, 12])

In [91]:
arr[:,2:3]

array([[ 3],
       [ 7],
       [11]])

In [92]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1[0]

array([1, 2, 3])

In [95]:
arr1[1]

array([4, 5, 6])

In [97]:
arr1[1,2]

6

In [98]:
arr[0,1]

2

In [100]:
arr1[0:,1:2]

array([[2],
       [5]])

In [101]:
arr1[1:,:2]

array([[4, 5]])

In [103]:
arr1[1:,:1]

array([[4]])

In [104]:
## Modifying array elements 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
arr[0][1] = 23

In [106]:
arr

array([[ 1, 23,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
arr[2,3] =10
arr

array([[ 1, 23,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 10]])

In [111]:
arr[2:] =12
arr

array([[ 1, 23,  3,  4],
       [ 5,  6,  7,  8],
       [12, 12, 12, 12]])

In [113]:
arr[2:,:3] = 10
arr

array([[ 1, 23,  3,  4],
       [ 5,  6,  7,  8],
       [10, 10, 10, 12]])

In [115]:
arr[0:2 , :1] = 13
arr

array([[13, 23,  3,  4],
       [13,  6,  7,  8],
       [10, 10, 10, 12]])

In [117]:
## Statistical Concept ( Normalization )
## mean is 0 and standard deviation is 1 
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [119]:
## Statistical functions 

# mean 
mean1 = np.mean(data)
print(mean1)

#median
median1 = np.median(data)
print(median1)

#standard deviation
std = np.std(data)
print(std)

#variance 
var = np.var(data)
print(var)


3.0
3.0
1.4142135623730951
2.0


In [121]:
## Logical Operations 

data = np.arange(0,11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
data > 5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [123]:
data < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [124]:
data == 10

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [126]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [128]:
data[data  < 4]

array([0, 1, 2, 3])

In [129]:
data[data ==10]

array([10])

In [131]:
data[(data > 5) & (data < 10)]

array([6, 7, 8, 9])

In [137]:
data[(data ==5) | (data == 10)]

array([ 5, 10])

In [138]:
data[data >= 3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
data[data <=4 ]

array([0, 1, 2, 3, 4])